# Form implementation generated from reading ui file 'createLocation.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 475)
        self.lbl_location = QtWidgets.QLabel(parent=Dialog)
        self.lbl_location.setGeometry(QtCore.QRect(160, 50, 151, 21))
        self.lbl_location.setObjectName("lbl_location")
        self.lbl_name = QtWidgets.QLabel(parent=Dialog)
        self.lbl_name.setGeometry(QtCore.QRect(160, 100, 151, 21))
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_description = QtWidgets.QLabel(parent=Dialog)
        self.lbl_description.setGeometry(QtCore.QRect(160, 160, 151, 21))
        self.lbl_description.setObjectName("lbl_description")
        self.ln_location = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_location.setGeometry(QtCore.QRect(160, 70, 151, 20))
        self.ln_location.setObjectName("ln_location")
        self.ln_description = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_description.setGeometry(QtCore.QRect(160, 190, 151, 20))
        self.ln_description.setObjectName("ln_description")
        self.btn_save = QtWidgets.QPushButton(parent=Dialog)
        self.btn_save.setGeometry(QtCore.QRect(200, 400, 81, 41))
        self.btn_save.setObjectName("btn_save")
        self.ln_name = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_name.setGeometry(QtCore.QRect(160, 130, 151, 20))
        self.ln_name.setObjectName("ln_name")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_location.setText(_translate("Dialog", "Id ubicacion"))
        self.lbl_name.setText(_translate("Dialog", "Nombre"))
        self.lbl_description.setText(_translate("Dialog", "Descripcion"))
        self.btn_save.setText(_translate("Dialog", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
