from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 475)
        self.lbl_partId = QtWidgets.QLabel(parent=Dialog)
        self.lbl_partId.setGeometry(QtCore.QRect(50, 50, 151, 21))
        self.lbl_partId.setObjectName("lbl_partId")
        self.lbl_serial = QtWidgets.QLabel(parent=Dialog)
        self.lbl_serial.setGeometry(QtCore.QRect(50, 100, 151, 21))
        self.lbl_serial.setObjectName("lbl_serial")
        self.lbl_name = QtWidgets.QLabel(parent=Dialog)
        self.lbl_name.setGeometry(QtCore.QRect(50, 180, 151, 21))
        self.lbl_name.setObjectName("lbl_name")
        self.ln_idparte = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_idparte.setGeometry(QtCore.QRect(50, 70, 151, 20))
        self.ln_idparte.setObjectName("ln_idparte")
        self.ln_name = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_name.setGeometry(QtCore.QRect(50, 200, 151, 20))
        self.ln_name.setObjectName("ln_name")
        self.lbl_brand = QtWidgets.QLabel(parent=Dialog)
        self.lbl_brand.setGeometry(QtCore.QRect(60, 230, 151, 21))
        self.lbl_brand.setObjectName("lbl_brand")
        self.ln_brand = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_brand.setGeometry(QtCore.QRect(50, 250, 151, 20))
        self.ln_brand.setObjectName("ln_brand")
        self.ln_model = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_model.setGeometry(QtCore.QRect(50, 310, 151, 20))
        self.ln_model.setObjectName("ln_model")
        self.lbl_model = QtWidgets.QLabel(parent=Dialog)
        self.lbl_model.setGeometry(QtCore.QRect(60, 280, 151, 21))
        self.lbl_model.setObjectName("lbl_model")
        self.btn_save = QtWidgets.QPushButton(parent=Dialog)
        self.btn_save.setGeometry(QtCore.QRect(200, 400, 81, 41))
        self.btn_save.setObjectName("btn_save")
        self.lbl_descrip = QtWidgets.QLabel(parent=Dialog)
        self.lbl_descrip.setGeometry(QtCore.QRect(280, 50, 151, 21))
        self.lbl_descrip.setObjectName("lbl_descrip")
        self.ln_descrip = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_descrip.setGeometry(QtCore.QRect(280, 70, 151, 20))
        self.ln_descrip.setObjectName("ln_descrip")
        self.ln_serial = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_serial.setGeometry(QtCore.QRect(50, 130, 151, 20))
        self.ln_serial.setObjectName("ln_serial")
        self.lbl_buyDate = QtWidgets.QLabel(parent=Dialog)
        self.lbl_buyDate.setGeometry(QtCore.QRect(280, 100, 151, 21))
        self.lbl_buyDate.setObjectName("lbl_buyDate")
        self.lbl_warantee = QtWidgets.QLabel(parent=Dialog)
        self.lbl_warantee.setGeometry(QtCore.QRect(280, 170, 151, 21))
        self.lbl_warantee.setObjectName("lbl_warantee")
        self.lbl_deviceId = QtWidgets.QLabel(parent=Dialog)
        self.lbl_deviceId.setGeometry(QtCore.QRect(280, 230, 151, 21))
        self.lbl_deviceId.setObjectName("lbl_deviceId")
        self.lbl_providerId = QtWidgets.QLabel(parent=Dialog)
        self.lbl_providerId.setGeometry(QtCore.QRect(280, 290, 151, 21))
        self.lbl_providerId.setObjectName("lbl_providerId")
        self.ln_buyDate = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_buyDate.setGeometry(QtCore.QRect(280, 130, 151, 20))
        self.ln_buyDate.setObjectName("ln_buyDate")
        self.ln_warantee = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_warantee.setGeometry(QtCore.QRect(280, 200, 151, 20))
        self.ln_warantee.setObjectName("ln_warantee")
        self.ln_deviceId = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_deviceId.setGeometry(QtCore.QRect(280, 250, 151, 20))
        self.ln_deviceId.setObjectName("ln_deviceId")
        self.ln_providerId = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_providerId.setGeometry(QtCore.QRect(280, 310, 151, 20))
        self.ln_providerId.setObjectName("ln_providerId")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_partId.setText(_translate("Dialog", "Id Parte"))
        self.lbl_serial.setText(_translate("Dialog", "Serial"))
        self.lbl_name.setText(_translate("Dialog", "Nombre"))
        self.lbl_brand.setText(_translate("Dialog", "Marca"))
        self.lbl_model.setText(_translate("Dialog", "Modelo"))
        self.btn_save.setText(_translate("Dialog", "Guardar"))
        self.lbl_descrip.setText(_translate("Dialog", "Descripcion"))
        self.lbl_buyDate.setText(_translate("Dialog", "fecha Compra"))
        self.lbl_warantee.setText(_translate("Dialog", "Garantia"))
        self.lbl_deviceId.setText(_translate("Dialog", "Id Equipo"))
        self.lbl_providerId.setText(_translate("Dialog", "Id proveedor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
