from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 475)
        self.lbl_softwareId = QtWidgets.QLabel(parent=Dialog)
        self.lbl_softwareId.setGeometry(QtCore.QRect(50, 50, 151, 21))
        self.lbl_softwareId.setObjectName("lbl_softwareId")
        self.lbl_name = QtWidgets.QLabel(parent=Dialog)
        self.lbl_name.setGeometry(QtCore.QRect(50, 100, 151, 21))
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_version = QtWidgets.QLabel(parent=Dialog)
        self.lbl_version.setGeometry(QtCore.QRect(50, 160, 151, 21))
        self.lbl_version.setObjectName("lbl_version")
        self.ln_softwareId = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_softwareId.setGeometry(QtCore.QRect(50, 70, 151, 20))
        self.ln_softwareId.setObjectName("ln_softwareId")
        self.ln_version = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_version.setGeometry(QtCore.QRect(50, 190, 151, 20))
        self.ln_version.setObjectName("ln_version")
        self.lbl_instKey = QtWidgets.QLabel(parent=Dialog)
        self.lbl_instKey.setGeometry(QtCore.QRect(50, 210, 151, 21))
        self.lbl_instKey.setObjectName("lbl_instKey")
        self.ln_instKey = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_instKey.setGeometry(QtCore.QRect(50, 240, 151, 20))
        self.ln_instKey.setObjectName("ln_instKey")
        self.btn_save = QtWidgets.QPushButton(parent=Dialog)
        self.btn_save.setGeometry(QtCore.QRect(200, 400, 81, 41))
        self.btn_save.setObjectName("btn_save")
        self.lbl_quantLic = QtWidgets.QLabel(parent=Dialog)
        self.lbl_quantLic.setGeometry(QtCore.QRect(280, 50, 151, 21))
        self.lbl_quantLic.setObjectName("lbl_quantLic")
        self.ln_quantLic = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_quantLic.setGeometry(QtCore.QRect(280, 70, 151, 20))
        self.ln_quantLic.setObjectName("ln_quantLic")
        self.ln_name = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_name.setGeometry(QtCore.QRect(50, 130, 151, 20))
        self.ln_name.setObjectName("ln_name")
        self.lbl_validity = QtWidgets.QLabel(parent=Dialog)
        self.lbl_validity.setGeometry(QtCore.QRect(280, 100, 151, 21))
        self.lbl_validity.setObjectName("lbl_validity")
        self.lbl_deviceId_2 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_deviceId_2.setGeometry(QtCore.QRect(280, 160, 151, 21))
        self.lbl_deviceId_2.setObjectName("lbl_deviceId_2")
        self.lbl_providerId = QtWidgets.QLabel(parent=Dialog)
        self.lbl_providerId.setGeometry(QtCore.QRect(280, 220, 151, 21))
        self.lbl_providerId.setObjectName("lbl_providerId")
        self.ln_validity = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_validity.setGeometry(QtCore.QRect(280, 130, 151, 20))
        self.ln_validity.setObjectName("ln_validity")
        self.ln_deviceId = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_deviceId.setGeometry(QtCore.QRect(280, 190, 151, 20))
        self.ln_deviceId.setObjectName("ln_deviceId")
        self.ln_providerId = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_providerId.setGeometry(QtCore.QRect(280, 240, 151, 20))
        self.ln_providerId.setObjectName("ln_providerId")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_softwareId.setText(_translate("Dialog", "Id Software"))
        self.lbl_name.setText(_translate("Dialog", "Nombre"))
        self.lbl_version.setText(_translate("Dialog", "Version"))
        self.lbl_instKey.setText(_translate("Dialog", "llave de instalacion"))
        self.btn_save.setText(_translate("Dialog", "Guardar"))
        self.lbl_quantLic.setText(_translate("Dialog", "cantidad de licencias"))
        self.lbl_validity.setText(_translate("Dialog", "vigencia"))
        self.lbl_deviceId_2.setText(_translate("Dialog", "Id equipo"))
        self.lbl_providerId.setText(_translate("Dialog", "Id proveedor"))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
