# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(315, 279)
        self.lbl_location = QtWidgets.QLabel(parent=Dialog)
        self.lbl_location.setGeometry(QtCore.QRect(100, 40, 151, 21))
        self.lbl_location.setObjectName("lbl_location")
        self.lbl_password = QtWidgets.QLabel(parent=Dialog)
        self.lbl_password.setGeometry(QtCore.QRect(100, 100, 151, 21))
        self.lbl_password.setObjectName("lbl_password")
        self.ln_userName = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_userName.setGeometry(QtCore.QRect(100, 70, 151, 20))
        self.ln_userName.setObjectName("ln_userName")
        self.btn_save = QtWidgets.QPushButton(parent=Dialog)
        self.btn_save.setGeometry(QtCore.QRect(140, 160, 81, 41))
        self.btn_save.setObjectName("btn_save")
        self.ln_password = QtWidgets.QLineEdit(parent=Dialog)
        self.ln_password.setGeometry(QtCore.QRect(100, 120, 151, 20))
        self.ln_password.setObjectName("ln_password")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_location.setText(_translate("Dialog", "USUARIO"))
        self.lbl_password.setText(_translate("Dialog", "CONTRASENA"))
        self.btn_save.setText(_translate("Dialog", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
